[startup.sshdkeys]
name = "bash"
after = ["init"]

[startup.sshdkeys.args]
script = """
ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N '' -t rsa
ssh-keygen -f /etc/ssh/ssh_host_dsa_key -N '' -t dsa
ssh-keygen -f /etc/ssh/ssh_host_ecdsa_key -N '' -t ecdsa -b 521
ssh-keygen -f /etc/ssh/ssh_host_ed25519_key -N '' -t ed25519
"""

[startup.sshd]
name = "core.system"
after = ["sshdkeys"]

[startup.sshd.args]
name = "/usr/sbin/sshd"
args = ["-e", "-D"]
