#WARNING:
# This redis instance is required for core0/coreX communication and must not be removed or modified unless you really really
# know what you are doing.
#
# Code assumes that this socket is available in the given location

[startup.redis-private]
name = "core.system"

[startup.redis-private.args]
name = "redis-server"
args = ["--unixsocket", "/var/run/redis.socket", "--port", "0"]

[startup.redis-public]
name = "core.system"

[startup.redis-public.args]
name = "redis-server"
args = ["--bind", "0.0.0.0", "--port", "6379"]