[startup.krnlog]
name = "bash"
after = ["init"]

[startup.krnlog.args]
script = """
#!/bin/ash
hexhost=$(echo \"{core0kmsg}\" | hexdump -e '\"%x\"')

if [ \"$hexhost\" == \"726f637b6d6b3065a7d6773\" ]; then
    echo \"core0 logs kernel message disabled\"
    exit 0
fi


tail -f /var/log/core.log | tee -a /dev/kmsg > /dev/null
"""
