[startup.modprobecustom]
name = "bash"
after = ["init"]
running_delay = -1

[startup.modprobecustom.args]
stdin = """
modprobe fuse
modprobe btrfs
modprobe tun
modprobe br_netfilter

echo never > /sys/kernel/mm/transparent_hugepage/enabled
"""
