[startup.modprobecustom]
name = "bash"
after = ["init"]
running_delay = -1

[startup.modprobecustom.args]
script = """
modprobe fuse
modprobe btrfs
modprobe tun
modprobe br_netfilter

echo never > /sys/kernel/mm/transparent_hugepage/enabled

ulimit -n 524288
"""
