[startup.udevd]
name = "core.system"

[startup.udevd.args]
name = "udevd"
args = ["--daemon"]

[startup.udevtrigger]
name = "bash"
after = ["udevd"]
running_delay = -1

[startup.udevtrigger.args]
stdin = """
udevadm trigger --action=add; udevadm settle
"""
